GET http://localhost:4000/api/packages/

###
POST http://localhost:4000/api/packages/
Content-Type: application/json

{
  "type": "tipo",
  "property": "",
  "car": "",
  "reserve": "",
  "medicalAssistance": ""
}
###
POST http://localhost:4000/api/packages/
Content-Type: application/json

{
  "type": "tipo"
}

###
DELETE http://localhost:4000/api/packages/65270018f480d7598942f264
